pipeline:
  project_name: "EnzOpt-ML"
  version: "1.0.0"
  log_level: "INFO"

phase1_design:
  model_name: "facebook/esm2_t30_150M_UR50D"
  target_name: "IsPETase_WT"
  wild_type_sequence: "MNFPRASRLMQAAVLGGLMAVSAAATAQTNPYARGPNPTAASLEASAGPFTVRSFTVSRPSGYGAGTVYYPTNAGGTVGAIAIVPGYTARQSSIKWWGPRLASHGFVVITIDTNSTLDQPSSRSSQQMAALRQVASLNGTSSSPIYGKVDTARMGVMGWSMGGGGSLISAANNPSLKAAAPQAPWDSSTNFSSVTVPTLIFACENDSIAPVNSSALPIYDSMSRNAKQFLEINGGSHSCANSGSTNQALIGKKGVAMTKQAILANGGSLSGAALNPPN"
  top_n_variants: 3  # <-- Set this to 3 for quick end-to-end validation
  mutation_score_threshold: 0.0

database:
  db_name: "data/enzopt_pipeline.db"
